export const ENDPOINTS = {
  sanctumCsrfCookie: '/sanctum/csrf-cookie',
  authLogin: '/auth/login',
  authRegister: '/auth/register',
  authMe: '/auth/me',
  authLogout: '/auth/logout',
  authForgotPassword: '/auth/forgot-password',
  authVerifyResetCode: '/auth/forgot-password/verify',
  authResetPassword: '/auth/reset-password',
  authGoogleRedirect: '/auth/google/redirect',
  clinics: '/clinics',
  clinicServices: (branchId: number) => `/clinics/${branchId}/services`,
  clinicSlots: (branchId: number, serviceId: number) =>
    `/clinics/${branchId}/services/${serviceId}/slots`,
  locationProvinces: '/locations/provinces',
  locationDistricts: (provinceId: number) =>
    `/locations/provinces/${provinceId}/districts`,
  locationWards: (districtId: number) =>
    `/locations/districts/${districtId}/wards`,
  customerAddresses: '/customer/addresses',
  customerAddress: (addressId: string) => `/customer/addresses/${addressId}`,
  customerAddressDefault: (addressId: string) =>
    `/customer/addresses/${addressId}/default`,
  customerShippingQuote: '/customer/shipping/quote',
  customerWallet: '/customer/wallet',
  customerOrders: '/customer/orders',
  customerCheckoutPreview: '/customer/orders/preview',
  customerOrder: (orderId: number) => `/customer/orders/${orderId}`,
  customerOrderPayment: (orderId: number) => `/customer/orders/${orderId}/payment`,
  customerOrderVnPay: (orderId: number) => `/customer/orders/${orderId}/payment/vnpay`,
  vnPayReturn: '/payments/vnpay/return',
  branches: '/branches',
  products: '/products',
  adminDashboard: '/admin/dashboard',
  adminCustomers: '/admin/customers',
  adminCustomer: (id: number | string) => `/admin/customers/${id}`,
  adminCustomerSkinProfile: (id: number | string) => `/admin/customers/${id}/skin-profile`,
  adminProducts: '/admin/products',
  adminProduct: (id: number | string) => `/admin/products/${id}`,
  adminCategories: '/admin/categories',
  adminCategory: (id: number | string) => `/admin/categories/${id}`,
  adminBrands: '/admin/brands',
  adminBrand: (id: number | string) => `/admin/brands/${id}`,
  adminInventory: '/admin/inventory',
  adminInventoryAdjust: (id: number | string) => `/admin/inventory/${id}/adjust`,
  adminInventoryTransactions: (id: number | string) => `/admin/inventory/${id}/transactions`,
  adminPromotions: '/admin/promotions',
  adminPromotion: (id: number | string) => `/admin/promotions/${id}`,
  adminPromotionUsage: (id: number | string) => `/admin/promotions/${id}/usage-stats`,
  adminReviews: '/admin/reviews',
  adminReview: (id: number | string) => `/admin/reviews/${id}`,
  adminBranches: '/admin/branches',
  adminBranch: (id: number | string) => `/admin/branches/${id}`,
  adminStaff: '/admin/staff',
  adminStaffMember: (id: number | string) => `/admin/staff/${id}`,
  adminOrders: '/admin/orders',
  adminOrder: (id: number | string) => `/admin/orders/${id}`,
  adminOrderAction: (id: number | string, action: string) => `/admin/orders/${id}/${action}`,
  adminRefunds: '/admin/refunds',
  adminRefund: (id: number | string) => `/admin/refunds/${id}`,
  adminRefundAction: (id: number | string, action: string) => `/admin/refunds/${id}/${action}`,
  adminAppointments: '/admin/appointments',
  adminAppointment: (id: number | string) => `/admin/appointments/${id}`,
  adminAppointmentAction: (id: number | string, action: string) => `/admin/appointments/${id}/${action}`,
} as const
