export const ROUTE_NAMES = {
  onboarding: 'onboarding',
  login: 'login',
  register: 'register',
  forgotPassword: 'forgot-password',
  verifyResetCode: 'verify-reset-code',
  resetPassword: 'reset-password',
  googleCallback: 'google-callback',
  foundation: 'foundation',
  products: 'products',
  productDetail: 'product-detail',
  favorites: 'favorites',
  cart: 'cart',
  checkout: 'checkout',
  skinCare: 'skin-care',
  forbidden: 'forbidden',
  notFound: 'not-found',
} as const

export const ROUTE_PATHS = {
  onboarding: '/onboarding',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  verifyResetCode: '/verify-reset-code',
  resetPassword: '/reset-password',
  googleCallback: '/auth/google/callback',
  foundation: '/',
  products: '/products',
  productDetail: '/products/:slug',
  favorites: '/favorites',
  cart: '/cart',
  checkout: '/checkout',
  skinCare: '/skin-care',
  forbidden: '/forbidden',
  notFoundExample: '/khong-ton-tai',
} as const
